# Generated by Django 5.1.4 on 2025-01-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalprojectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unique_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
