# Generated by Django 5.1.4 on 2025-01-09 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalprojectapp', '0002_user_unique_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='unique_name',
        ),
    ]
