# Generated by Django 5.1.4 on 2025-01-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalprojectapp', '0008_receptionists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionists',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
