# Generated by Django 5.1.4 on 2025-01-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalprojectapp', '0009_alter_receptionists_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionists',
            name='hire_date',
            field=models.DateField(null=True),
        ),
    ]
