# Generated by Django 5.1.4 on 2025-01-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalprojectapp', '0011_alter_receptionists_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='payment_status',
            new_name='confirmed',
        ),
        migrations.AddField(
            model_name='appointment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
